// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	providerv1beta1 "github.com/cs3org/go-cs3apis/cs3/storage/provider/v1beta1"
	registryv1beta1 "github.com/cs3org/go-cs3apis/cs3/storage/registry/v1beta1"
	mock "github.com/stretchr/testify/mock"
)

// PoolManager is an autogenerated mock type for the PoolManager type
type PoolManager struct {
	mock.Mock
}

// GetStorageProviderServiceClient provides a mock function with given fields: endpoint
func (_m *PoolManager) GetStorageProviderServiceClient(endpoint string) (providerv1beta1.ProviderAPIClient, error) {
	ret := _m.Called(endpoint)

	var r0 providerv1beta1.ProviderAPIClient
	if rf, ok := ret.Get(0).(func(string) providerv1beta1.ProviderAPIClient); ok {
		r0 = rf(endpoint)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(providerv1beta1.ProviderAPIClient)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(endpoint)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStorageRegistryClient provides a mock function with given fields: endpoint
func (_m *PoolManager) GetStorageRegistryClient(endpoint string) (registryv1beta1.RegistryAPIClient, error) {
	ret := _m.Called(endpoint)

	var r0 registryv1beta1.RegistryAPIClient
	if rf, ok := ret.Get(0).(func(string) registryv1beta1.RegistryAPIClient); ok {
		r0 = rf(endpoint)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(registryv1beta1.RegistryAPIClient)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(endpoint)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
